### ISSUE TITLE
infografia-Alvaro Froylan Pacheco Osorio 

### ISSUE THREAD

**Issue by Alvaro2-0** [SistemasTecTlaxiaco/actividad-1-infografia-Alvaro2-0-1#1]
[Infografía.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-Alvaro2-0-1/files/14250453/Infografia.pdf)

**Comment by irving1989** [comment]
Partes de la infografía (título, texto explicativo, gráficos, fuente, créditos): **4** - Todas las partes de la infografía se encuentran
Coherencia y pertinencia: **3** - Los elementos gráficos no están relacionados con el tema.
Organización de la información: **4** - La comprensión es clara y el tema está bien desarrollado.
Diseño de la infografía: **3** - Los textos y colores si combinan en armonía.
Creatividad: **3** - El diseño es bueno, pero podría mejorar

Total de puntos: 17/20

**Calificación: 17**

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
